server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:/moses-learning/microservices-spring-boot-chapter3/src/main/resources/config/licensingservice
